Category
pop-pin/backend-server pull request #14
Opened 2023-09-19 15:40 UTC by codrin2

2023-09-20 06:01 UTC, YanyChoi requested changes
리뷰 확인 부탁드려요
+ 테스트코드도 추가해주세요

2023-09-20 06:01 UTC, YanyChoi commented on src/main/java/com/poppin/backendserver/controller/CategoryController.java
> +@RequestMapping("v1/Category")
대문자는 빼주세요.

2023-09-20 06:01 UTC, YanyChoi commented on src/main/java/com/poppin/backendserver/entity/Location.java
> +    @OneToMany(mappedBy = "location", cascade = CascadeType.REMOVE)
이거 정확히 어떻게 작동하는건가요?

2023-09-23 10:03 UTC, codrin2 commented on src/main/java/com/poppin/backendserver/entity/Location.java
> +    @OneToMany(mappedBy = "location", cascade = CascadeType.REMOVE)
location이 일대다 연관관계 주인이고 CascadeType.REMOVE가 있으면 location이 삭제 되었을때 연관관계에 있던 애들이 주인이랑 같이 삭제됩니다. @JsonIgnore는 Fetch 타입을 Lazy로 사용했을 때 발생하는 에러를 막기위해 쓰는걸로 알고 있습니다.

2023-09-23 12:49 UTC, YanyChoi approved these changes
LGTM 👍

2023-09-23 12:50 UTC, merged