Heesang
pop-pin/backend-server pull request #3
Opened 2023-08-01 20:00 UTC by codrin2

location, review 전부 완료 및 location 부분 페이징(일단 완료했는데 맞게 했는지 테스트 해봐야함)
한번에 올려서 죄송해요..

2023-08-25 14:24 UTC, YanyChoi requested changes
수고하셨습니다.
리뷰 모시고 수정 조금 부탁드릴게요.
그리고 테스트 실패하고 있는데 확인 부탁드릴게요.

2023-08-25 14:24 UTC, YanyChoi commented on src/test/java/com/poppin/backendserver/controller/LocationControllerTest.java
> +        mockMvc.perform(get("/v1/locations/{location_id}", locationId))
GET 요청이면 결과값도 확인해야 하는데, response code 만 확인하면 안될 것 같아요.
만약 기능 구현이 다 안된 상태면 현재 상태로 놔두시고, 다 된 엔드포인트면 다 제대로 리턴하는지를 확인하는걸로 가시죠~

2023-08-25 14:24 UTC, YanyChoi commented on src/test/java/com/poppin/backendserver/controller/LocationControllerTest.java
> +                .andExpect(status().isOk());
여기도 GET요청이라 원래는 값을 확인해야해요.

2023-08-25 18:00 UTC, codrin2 commented on src/test/java/com/poppin/backendserver/controller/LocationControllerTest.java
> +        mockMvc.perform(get("/v1/locations/{location_id}", locationId))
네 수정할게요!

2023-08-27 01:41 UTC, YanyChoi approved these changes

2023-08-27 01:42 UTC, YanyChoi commented
@codrin2 LGTM 👍 머지해주시죠!

2023-08-27 01:49 UTC, merged